env:
  name: DISCO
  repos: [
          Red_Hat_Enterprise_Linux_7_Server_-_Extras_RPMs_x86_64,
          Red_Hat_Satellite_Tools_6_2_for_RHEL_7_Server_RPMs_x86_64,
          Red_Hat_Enterprise_Linux_7_Server_-_RH_Common_RPMs_x86_64_7Server,
         ]
